// config.js (auto-generated by GitHub Actions)
export const config = {
  GOOGLE_API_KEY: 'your-google-api-key-here',
  GOOGLE_CLIENT_ID: 'your-google-client-id-here',
  SPOTIFY_CLIENT_ID: 'your-spotify-client-id-here',
  SPOTIFY_CLIENT_SECRET: 'your-spotify-client-secret-here'
};
