name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Inject frontend config
        env:
          GOOGLE_API_KEY:      ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CLIENT_ID:    ${{ vars.GOOGLE_CLIENT_ID }}
          SPOTIFY_CLIENT_ID:   ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET:${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          cat > config.js <<EOF
export const config = {
  GOOGLE_API_KEY: "${GOOGLE_API_KEY}",
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}",
  SPOTIFY_CLIENT_ID: "${SPOTIFY_CLIENT_ID}",
  SPOTIFY_CLIENT_SECRET: "${SPOTIFY_CLIENT_SECRET}"
};
EOF

      - name: Show config.js contents
        run: cat config.js

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
