name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Inject frontend config
      run: |
        mkdir -p public
        echo "export const config = {" > config.js
        echo "  GOOGLE_API_KEY: '${{ secrets.GOOGLE_API_KEY }}'," >> config.js
        echo "  GOOGLE_CLIENT_ID: '${{ vars.GOOGLE_CLIENT_ID }}'," >> config.js
        echo "  SPOTIFY_CLIENT_ID: '${{ vars.SPOTIFY_CLIENTID }}'" >> config.js
        echo "};" >> config.js
        echo "  SPOTIFY_CLIENT_SECRET: '${{ secrets.SPOTIFY_CLIENT_SECRET }}'" >> config.js

    - name: Build project
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
